services:
  - type: web
    name: hajj-omra-booking-api
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 5001

  - type: web
    name: hajj-omra-booking-client
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        fromService:
          name: hajj-omra-booking-api
          type: web
          property: url 

  - type: web
    name: hajj-omra-booking-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run preview
    envVars:
      - key: VITE_API_URL
        value: https://hajj-omra-booking-api.onrender.com 